### ISSUE TITLE
Can't find this in npm

### ISSUE THREAD

**Issue by vimarjr** [francov/elasticsearch-scroll-stream#1]
Can't find this in npm

**Comment by francov** [comment]
You are right! This module has not been pushed on npm yet, but I'll do it as soon as possible.
In the mean time you can point your `package.json` dependency at this repo, this way:
```
...
"dependencies": {
   "elasicsearch-scroll-stream": "git://github.com/alcacoop/elasticsearch-scroll-stream.git"
}
```
Thank you!

**Comment by francov** [comment]
elasticsearch-scroll-stream is now on npmjs.com
