### ISSUE TITLE
OME when running against a large index

### ISSUE THREAD

**Issue by jalateras** [francov/elasticsearch-scroll-stream#3]
I am experiencing some OME when querying against a index with 50+ million rows. I was curious whether this has been reported previously. I get beween 1-2M rows before it exits. I eould hsvr thought that this should happen with a streaming interface.

**Comment by francov** [comment]
It has never happened to me to get an out of memory error here, neither using elastical interface nor elastic official client. My needs were to index under 1M documents, so I have never experienced this error.
Can you give me a stacktrace or message of this kind of error please?

**Comment by francov** [comment]
Ah, obviously the nodejs version too

**Comment by francov** [comment]
Please reopen this issue on the official repo [here](https://github.com/alcacoop/elasticsearch-scroll-stream). I'm going to close this now.
